### ISSUE TITLE
Unsupported layer type: LeakyReLU

### ISSUE THREAD

**Issue by TaeheeJeong** [uhfband/keras2caffe#17]
Can you add 'LeakyReLU'?

Traceback (most recent call last):
  File "convert.py", line 9, in <module>
    keras2caffe.convert(model, 'pix2pix_076720.prototxt', 'pix2pix_076720.caffemodel')
  File "../../keras2caffe/convert.py", line 381, in convert
    raise Exception('Unsupported layer type: '+layer_type)
Exception: Unsupported layer type: LeakyReLU

**Comment by uhfband** [comment]
I've added LeakyReLU, but not tested yet

**Comment by TaeheeJeong** [comment]
It passed, but another error flag comes out.
