### ISSUE TITLE
AttributeError: type object 'InputLayer' has no attribute '__name_'

### ISSUE THREAD

**Issue by nerddd** [uhfband/keras2caffe#9]
run convert_InceptionV4.py, already download inceptionv4.py from the url you provided.
error occured :`AttributeError: type object 'InputLayer' has no attribute '__name_'`

keras_version=2.1.2 already
I've tried python2.7 and python3.5, still exists this problem

Did someone encounter this problem?

convert_InceptionV3.py is not ok...

**Comment by uhfband** [comment]
Hi!
I had fixed this problem, should works now
